SET client_encoding = UTF8;

-- =============================================
-- BUSINESS INDUSTRIES DATA 2025
-- Nganh nghe cap 4: 100 records
-- =============================================

CREATE TABLE IF NOT EXISTS business_industries (
  id         SERIAL PRIMARY KEY,
  code       VARCHAR(20)  NOT NULL UNIQUE,
  name       VARCHAR(300) NOT NULL,
  level      SMALLINT     NOT NULL DEFAULT 4,
  parent_id  INT          NULL REFERENCES business_industries(id),
  status     VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP    DEFAULT NOW(),
  updated_at TIMESTAMP    DEFAULT NOW()
);

TRUNCATE TABLE business_industries RESTART IDENTITY CASCADE;

-- Nganh nghe cap 4 (100 records)
INSERT INTO business_industries (id, code, name, level, parent_id, status) VALUES
  (1, '0111', 'Trồng lúa', 4, NULL, 'ACTIVE'),
  (2, '0112', 'Trồng ngô và cây lương thực có hạt khác', 4, NULL, 'ACTIVE'),
  (3, '0113', 'Trồng cây lấy củ có chất bột', 4, NULL, 'ACTIVE'),
  (4, '0114', 'Trồng cây mía', 4, NULL, 'ACTIVE'),
  (5, '0115', 'Trồng cây thuốc lá, thuốc lào', 4, NULL, 'ACTIVE'),
  (6, '0116', 'Trồng cây lấy sợi', 4, NULL, 'ACTIVE'),
  (7, '0117', 'Trồng cây có hạt chứa dầu', 4, NULL, 'ACTIVE'),
  (8, '0118', 'Trồng rau, đậu các loại và trồng hoa, cây cảnh', 4, NULL, 'ACTIVE'),
  (9, '0119', 'Trồng cây hàng năm khác', 4, NULL, 'ACTIVE'),
  (10, '0121', 'Trồng cây ăn quả', 4, NULL, 'ACTIVE'),
  (11, '0122', 'Trồng cây lấy quả chứa dầu', 4, NULL, 'ACTIVE'),
  (12, '0123', 'Trồng cây điều', 4, NULL, 'ACTIVE'),
  (13, '0124', 'Trồng cây hồ tiêu', 4, NULL, 'ACTIVE'),
  (14, '0125', 'Trồng cây cao su', 4, NULL, 'ACTIVE'),
  (15, '0126', 'Trồng cây cà phê', 4, NULL, 'ACTIVE'),
  (16, '0127', 'Trồng cây chè', 4, NULL, 'ACTIVE'),
  (17, '0128', 'Trồng cây gia vị, cây dược liệu', 4, NULL, 'ACTIVE'),
  (18, '0129', 'Trồng cây lâu năm khác', 4, NULL, 'ACTIVE'),
  (19, '0130', 'Nhân và chăm sóc cây giống nông nghiệp', 4, NULL, 'ACTIVE'),
  (20, '0141', 'Chăn nuôi trâu, bò', 4, NULL, 'ACTIVE'),
  (21, '0142', 'Chăn nuôi ngựa, lừa, la', 4, NULL, 'ACTIVE'),
  (22, '0144', 'Chăn nuôi dê, cừu', 4, NULL, 'ACTIVE'),
  (23, '0145', 'Chăn nuôi lợn', 4, NULL, 'ACTIVE'),
  (24, '0146', 'Chăn nuôi gia cầm', 4, NULL, 'ACTIVE'),
  (25, '0149', 'Chăn nuôi khác', 4, NULL, 'ACTIVE'),
  (26, '0150', 'Trồng trọt, chăn nuôi hỗn hợp', 4, NULL, 'ACTIVE'),
  (27, '0161', 'Hoạt động dịch vụ trồng trọt', 4, NULL, 'ACTIVE'),
  (28, '0162', 'Hoạt động dịch vụ chăn nuôi', 4, NULL, 'ACTIVE'),
  (29, '0163', 'Hoạt động dịch vụ sau thu hoạch', 4, NULL, 'ACTIVE'),
  (30, '0164', 'Xử lý hạt giống để nhân giống', 4, NULL, 'ACTIVE'),
  (31, '0170', 'Săn bắt, đánh bẫy và hoạt động dịch vụ có liên quan', 4, NULL, 'ACTIVE'),
  (32, '0210', 'Trồng rừng và chăm sóc rừng', 4, NULL, 'ACTIVE'),
  (33, '0221', 'Khai thác gỗ', 4, NULL, 'ACTIVE'),
  (34, '0222', 'Khai thác lâm sản khác trừ gỗ', 4, NULL, 'ACTIVE'),
  (35, '0230', 'Thu nhặt sản phẩm từ rừng không phải gỗ và lâm sản khác', 4, NULL, 'ACTIVE'),
  (36, '0240', 'Hoạt động dịch vụ lâm nghiệp', 4, NULL, 'ACTIVE'),
  (37, '0311', 'Khai thác thuỷ sản biển', 4, NULL, 'ACTIVE'),
  (38, '0312', 'Khai thác thuỷ sản nội địa', 4, NULL, 'ACTIVE'),
  (39, '0321', 'Nuôi trồng thuỷ sản biển', 4, NULL, 'ACTIVE'),
  (40, '0322', 'Nuôi trồng thuỷ sản nội địa', 4, NULL, 'ACTIVE'),
  (41, '0323', 'Sản xuất giống thuỷ sản', 4, NULL, 'ACTIVE'),
  (42, '0510', 'Khai thác và thu gom than cứng', 4, NULL, 'ACTIVE'),
  (43, '0520', 'Khai thác và thu gom than non', 4, NULL, 'ACTIVE'),
  (44, '0610', 'Khai thác dầu thô', 4, NULL, 'ACTIVE'),
  (45, '0620', 'Khai thác khí đốt tự nhiên', 4, NULL, 'ACTIVE'),
  (46, '0710', 'Khai thác quặng sắt', 4, NULL, 'ACTIVE'),
  (47, '0721', 'Khai thác quặng uranium và quặng thorium', 4, NULL, 'ACTIVE'),
  (48, '0722', 'Khai thác quặng kim loại khác không chứa sắt', 4, NULL, 'ACTIVE'),
  (49, '0730', 'Khai thác quặng kim loại quí hiếm', 4, NULL, 'ACTIVE'),
  (50, '0810', 'Khai thác đá, cát, sỏi, đất sét', 4, NULL, 'ACTIVE'),
  (51, '0891', 'Khai thác khoáng hoá chất và khoáng phân bón', 4, NULL, 'ACTIVE'),
  (52, '0892', 'Khai thác và thu gom than bùn', 4, NULL, 'ACTIVE'),
  (53, '0893', 'Khai thác muối', 4, NULL, 'ACTIVE'),
  (54, '0899', 'Khai khoáng khác chưa được phân vào đâu', 4, NULL, 'ACTIVE'),
  (55, '0910', 'Hoạt động dịch vụ hỗ trợ khai thác dầu thô và khí tự nhiên', 4, NULL, 'ACTIVE'),
  (56, '0990', 'Hoạt động dịch vụ hỗ trợ khai thác mỏ và quặng khác', 4, NULL, 'ACTIVE'),
  (57, '1010', 'Chế biến, bảo quản thịt và các sản phẩm từ thịt', 4, NULL, 'ACTIVE'),
  (58, '1020', 'Chế biến, bảo quản thuỷ sản và các sản phẩm từ thuỷ sản', 4, NULL, 'ACTIVE'),
  (59, '1030', 'Chế biến và bảo quản rau quả', 4, NULL, 'ACTIVE'),
  (60, '1040', 'Sản xuất dầu, mỡ động, thực vật', 4, NULL, 'ACTIVE'),
  (61, '1050', 'Chế biến sữa và các sản phẩm từ sữa', 4, NULL, 'ACTIVE'),
  (62, '1061', 'Xay xát và sản xuất bột thô', 4, NULL, 'ACTIVE'),
  (63, '1062', 'Sản xuất tinh bột và các sản phẩm từ tinh bột', 4, NULL, 'ACTIVE'),
  (64, '1071', 'Sản xuất các loại bánh từ bột', 4, NULL, 'ACTIVE'),
  (65, '1072', 'Sản xuất đường', 4, NULL, 'ACTIVE'),
  (66, '1073', 'Sản xuất ca cao, sôcôla và mứt kẹo', 4, NULL, 'ACTIVE'),
  (67, '1074', 'Sản xuất mì ống, mỳ sợi và sản phẩm tương tự', 4, NULL, 'ACTIVE'),
  (68, '1075', 'Sản xuất món ăn, thức ăn chế biến sẵn', 4, NULL, 'ACTIVE'),
  (69, '1076', 'Sản xuất chè', 4, NULL, 'ACTIVE'),
  (70, '1077', 'Sản xuất cà phê', 4, NULL, 'ACTIVE'),
  (71, '1079', 'Sản xuất thực phẩm khác chưa được phân vào đâu', 4, NULL, 'ACTIVE'),
  (72, '1080', 'Sản xuất thức ăn gia súc, gia cầm và thuỷ sản', 4, NULL, 'ACTIVE'),
  (73, '1101', 'Chưng, tinh cất và pha chế các loại rượu mạnh', 4, NULL, 'ACTIVE'),
  (74, '1102', 'Sản xuất rượu vang', 4, NULL, 'ACTIVE'),
  (75, '1103', 'Sản xuất bia và mạch nha ủ men bia', 4, NULL, 'ACTIVE'),
  (76, '1104', 'Sản xuất đồ uống không cồn, nước khoáng', 4, NULL, 'ACTIVE'),
  (77, '1200', 'Sản xuất sản phẩm thuốc lá', 4, NULL, 'ACTIVE'),
  (78, '1311', 'Sản xuất sợi', 4, NULL, 'ACTIVE'),
  (79, '1312', 'Sản xuất vải dệt thoi', 4, NULL, 'ACTIVE'),
  (80, '1313', 'Hoàn thiện sản phẩm dệt', 4, NULL, 'ACTIVE'),
  (81, '1391', 'Sản xuất vải dệt kim, vải đan móc và vải không dệt khác', 4, NULL, 'ACTIVE'),
  (82, '1392', 'Sản xuất hàng dệt sẵn (trừ trang phục)', 4, NULL, 'ACTIVE'),
  (83, '1393', 'Sản xuất thảm, chăn, đệm', 4, NULL, 'ACTIVE'),
  (84, '1394', 'Sản xuất các loại dây bện và lưới', 4, NULL, 'ACTIVE'),
  (85, '1399', 'Sản xuất các loại hàng dệt khác chưa được phân vào đâu', 4, NULL, 'ACTIVE'),
  (86, '1410', 'May trang phục (trừ trang phục từ da lông thú)', 4, NULL, 'ACTIVE'),
  (87, '1420', 'Sản xuất sản phẩm từ da lông thú', 4, NULL, 'ACTIVE'),
  (88, '1430', 'Sản xuất trang phục dệt kim, đan móc', 4, NULL, 'ACTIVE'),
  (89, '1511', 'Thuộc, sơ chế da; sơ chế và nhuộm da lông thú', 4, NULL, 'ACTIVE'),
  (90, '1512', 'Sản xuất vali, túi xách và các loại tương tự, sản xuất yên đệm', 4, NULL, 'ACTIVE'),
  (91, '1520', 'Sản xuất giày, dép', 4, NULL, 'ACTIVE'),
  (92, '1610', 'Cưa, xẻ, bào gỗ và bảo quản gỗ', 4, NULL, 'ACTIVE'),
  (93, '1621', 'Sản xuất gỗ dán, gỗ lạng, ván ép và ván mỏng khác', 4, NULL, 'ACTIVE'),
  (94, '1622', 'Sản xuất đồ gỗ xây dựng', 4, NULL, 'ACTIVE'),
  (95, '1623', 'Sản xuất bao bì bằng gỗ', 4, NULL, 'ACTIVE'),
  (96, '1629', 'Sản xuất sản phẩm khác từ gỗ; sản xuất sản phẩm từ tre, nứa, rơm, rạ và vật liệu tết bện', 4, NULL, 'ACTIVE'),
  (97, '1701', 'Sản xuất bột giấy, giấy và bìa', 4, NULL, 'ACTIVE'),
  (98, '1702', 'Sản xuất giấy nhăn, bìa nhăn, bao bì từ giấy và bìa', 4, NULL, 'ACTIVE'),
  (99, '1709', 'Sản xuất các sản phẩm khác từ giấy và bìa chưa được phân vào đâu', 4, NULL, 'ACTIVE'),
  (100, '1811', 'In ấn', 4, NULL, 'ACTIVE');

SELECT setval(pg_get_serial_sequence('business_industries', 'id'), (SELECT MAX(id) FROM business_industries));

-- Kiem tra
SELECT COUNT(*) AS tong_nganh_nghe FROM business_industries;