-- =================================================================
-- Danh mục nghề nghiệp Việt Nam (QĐ 34/2020/QĐ-TTg)
-- 100 mã cấp 4 trải đều 10 nhóm, phù hợp với báo cáo TNLĐ
-- Bảng: professions | Cột: code (varchar), name, level, status, parent_id
-- =================================================================

-- Cấp 1 (10 nhóm chính)
INSERT INTO professions (code, name, level, status) VALUES
  ('0', 'Lực lượng vũ trang', 'Cấp 1', true),
  ('1', 'Lãnh đạo, quản lý trong các ngành, các cấp và các đơn vị', 'Cấp 1', true),
  ('2', 'Nhà chuyên môn bậc cao', 'Cấp 1', true),
  ('3', 'Kỹ thuật viên và nhân viên trợ lý chuyên môn', 'Cấp 1', true),
  ('4', 'Nhân viên văn phòng', 'Cấp 1', true),
  ('5', 'Nhân viên dịch vụ và bán hàng', 'Cấp 1', true),
  ('6', 'Lao động có kỹ năng trong nông nghiệp, lâm nghiệp và thủy sản', 'Cấp 1', true),
  ('7', 'Lao động thủ công và các nghề có liên quan khác', 'Cấp 1', true),
  ('8', 'Thợ vận hành máy móc, thiết bị và lắp ráp', 'Cấp 1', true),
  ('9', 'Lao động giản đơn', 'Cấp 1', true)
ON CONFLICT (code) DO UPDATE SET level = EXCLUDED.level;

-- Cấp 2
INSERT INTO professions (code, name, level, status, parent_id) VALUES
  ('01', 'Lực lượng quân đội', 'Cấp 2', true, (SELECT id FROM professions WHERE code = '0')),
  ('02', 'Lực lượng công an', 'Cấp 2', true, (SELECT id FROM professions WHERE code = '0')),
  ('03', 'Cơ yếu và lực lượng vũ trang khác', 'Cấp 2', true, (SELECT id FROM professions WHERE code = '0')),
  ('17', 'Nhà quản lý sản xuất, kinh doanh và dịch vụ', 'Cấp 2', true, (SELECT id FROM professions WHERE code = '1')),
  ('21', 'Nhà chuyên môn trong lĩnh vực khoa học và kỹ thuật', 'Cấp 2', true, (SELECT id FROM professions WHERE code = '2')),
  ('22', 'Nhà chuyên môn về y tế', 'Cấp 2', true, (SELECT id FROM professions WHERE code = '2')),
  ('31', 'Kỹ thuật viên trong lĩnh vực khoa học và kỹ thuật', 'Cấp 2', true, (SELECT id FROM professions WHERE code = '3')),
  ('41', 'Nhân viên văn phòng thực hiện công việc chung', 'Cấp 2', true, (SELECT id FROM professions WHERE code = '4')),
  ('43', 'Nhân viên kế toán, thống kê, tài chính và dịch vụ liên quan', 'Cấp 2', true, (SELECT id FROM professions WHERE code = '4')),
  ('44', 'Nhân viên hỗ trợ văn phòng khác', 'Cấp 2', true, (SELECT id FROM professions WHERE code = '4')),
  ('51', 'Nhân viên dịch vụ cá nhân', 'Cấp 2', true, (SELECT id FROM professions WHERE code = '5')),
  ('52', 'Người bán hàng', 'Cấp 2', true, (SELECT id FROM professions WHERE code = '5')),
  ('53', 'Nhân viên chăm sóc cá nhân', 'Cấp 2', true, (SELECT id FROM professions WHERE code = '5')),
  ('54', 'Nhân viên bảo vệ và an ninh', 'Cấp 2', true, (SELECT id FROM professions WHERE code = '5')),
  ('61', 'Lao động có kỹ năng trong nông nghiệp, lâm nghiệp và thủy sản theo định hướng thị trường', 'Cấp 2', true, (SELECT id FROM professions WHERE code = '6')),
  ('62', 'Lao động có kỹ năng trong khai thác thủy sản và đánh bẫy', 'Cấp 2', true, (SELECT id FROM professions WHERE code = '6')),
  ('63', 'Lao động tự cung tự cấp trong nông nghiệp, lâm nghiệp và thủy sản', 'Cấp 2', true, (SELECT id FROM professions WHERE code = '6')),
  ('71', 'Lao động xây dựng và thợ có liên quan (trừ thợ điện)', 'Cấp 2', true, (SELECT id FROM professions WHERE code = '7')),
  ('81', 'Thợ vận hành máy và thiết bị khai khoáng và sản xuất', 'Cấp 2', true, (SELECT id FROM professions WHERE code = '8')),
  ('82', 'Thợ lắp ráp', 'Cấp 2', true, (SELECT id FROM professions WHERE code = '8')),
  ('83', 'Lái xe và thợ vận hành thiết bị chuyển động', 'Cấp 2', true, (SELECT id FROM professions WHERE code = '8')),
  ('91', 'Lao động dọn vệ sinh và lao động giản đơn khác', 'Cấp 2', true, (SELECT id FROM professions WHERE code = '9')),
  ('92', 'Lao động giản đơn trong nông nghiệp, lâm nghiệp và thủy sản', 'Cấp 2', true, (SELECT id FROM professions WHERE code = '9')),
  ('93', 'Lao động giản đơn trong khai khoáng, xây dựng, chế tạo và giao thông', 'Cấp 2', true, (SELECT id FROM professions WHERE code = '9')),
  ('96', 'Lao động giản đơn khác', 'Cấp 2', true, (SELECT id FROM professions WHERE code = '9'))
ON CONFLICT (code) DO UPDATE SET level = EXCLUDED.level, parent_id = EXCLUDED.parent_id;

-- Cấp 3
INSERT INTO professions (code, name, level, status, parent_id) VALUES
  ('011', 'Sĩ quan quân đội', 'Cấp 3', true, (SELECT id FROM professions WHERE code = '01')),
  ('012', 'Hạ sĩ quan, binh sĩ', 'Cấp 3', true, (SELECT id FROM professions WHERE code = '01')),
  ('013', 'Lực lượng khác trong quân đội', 'Cấp 3', true, (SELECT id FROM professions WHERE code = '01')),
  ('021', 'Sĩ quan công an', 'Cấp 3', true, (SELECT id FROM professions WHERE code = '02')),
  ('022', 'Hạ sĩ quan, chiến sĩ công an', 'Cấp 3', true, (SELECT id FROM professions WHERE code = '02')),
  ('023', 'Lực lượng khác trong công an', 'Cấp 3', true, (SELECT id FROM professions WHERE code = '02')),
  ('031', 'Cơ yếu', 'Cấp 3', true, (SELECT id FROM professions WHERE code = '03')),
  ('032', 'Lực lượng vũ trang khác', 'Cấp 3', true, (SELECT id FROM professions WHERE code = '03')),
  ('172', 'Giám đốc, Phó Giám đốc đơn vị sản xuất và triển khai thuộc tập đoàn lớn', 'Cấp 3', true, (SELECT id FROM professions WHERE code = '17')),
  ('174', 'Giám đốc, Phó Giám đốc công ty, doanh nghiệp, xí nghiệp nhỏ', 'Cấp 3', true, (SELECT id FROM professions WHERE code = '17')),
  ('214', 'Nhà chuyên môn về kỹ thuật (trừ kỹ thuật điện)', 'Cấp 3', true, (SELECT id FROM professions WHERE code = '21')),
  ('215', 'Kỹ sư kỹ thuật điện', 'Cấp 3', true, (SELECT id FROM professions WHERE code = '21')),
  ('216', 'Kiến trúc sư, nhà quy hoạch đô thị, kỹ sư giao thông và nhà thiết kế', 'Cấp 3', true, (SELECT id FROM professions WHERE code = '21')),
  ('226', 'Nhà chuyên môn về y tế khác', 'Cấp 3', true, (SELECT id FROM professions WHERE code = '22')),
  ('311', 'Kỹ thuật viên vật lý và kỹ thuật', 'Cấp 3', true, (SELECT id FROM professions WHERE code = '31')),
  ('312', 'Giám sát viên khai thác mỏ, sản xuất và xây dựng', 'Cấp 3', true, (SELECT id FROM professions WHERE code = '31')),
  ('313', 'Kỹ thuật viên kiểm soát, vận hành và điều khiển quy trình', 'Cấp 3', true, (SELECT id FROM professions WHERE code = '31')),
  ('411', 'Nhân viên văn phòng đa năng', 'Cấp 3', true, (SELECT id FROM professions WHERE code = '41')),
  ('412', 'Thư ký', 'Cấp 3', true, (SELECT id FROM professions WHERE code = '41')),
  ('431', 'Nhân viên về toán ứng dụng và tài chính', 'Cấp 3', true, (SELECT id FROM professions WHERE code = '43')),
  ('432', 'Nhân viên ghi chép nguyên vật liệu và vận chuyển', 'Cấp 3', true, (SELECT id FROM professions WHERE code = '43')),
  ('440', 'Nhân viên hỗ trợ văn phòng khác', 'Cấp 3', true, (SELECT id FROM professions WHERE code = '44')),
  ('511', 'Nhân viên hướng dẫn, tổ chức khách du lịch', 'Cấp 3', true, (SELECT id FROM professions WHERE code = '51')),
  ('512', 'Đầu bếp', 'Cấp 3', true, (SELECT id FROM professions WHERE code = '51')),
  ('513', 'Bồi bàn và người phục vụ quầy bar', 'Cấp 3', true, (SELECT id FROM professions WHERE code = '51')),
  ('514', 'Thợ làm tóc, thợ thẩm mỹ và các thợ có liên quan', 'Cấp 3', true, (SELECT id FROM professions WHERE code = '51')),
  ('516', 'Nhân viên bảo vệ, an ninh và phòng chống cháy nổ', 'Cấp 3', true, (SELECT id FROM professions WHERE code = '51')),
  ('521', 'Người bán hàng tại quầy, cửa hàng', 'Cấp 3', true, (SELECT id FROM professions WHERE code = '52')),
  ('532', 'Công nhân chăm sóc cá nhân tại nhà', 'Cấp 3', true, (SELECT id FROM professions WHERE code = '53')),
  ('541', 'Nhân viên bảo vệ, cảnh sát tư nhân', 'Cấp 3', true, (SELECT id FROM professions WHERE code = '54')),
  ('611', 'Lao động trồng trọt', 'Cấp 3', true, (SELECT id FROM professions WHERE code = '61')),
  ('612', 'Lao động chăn nuôi gia súc và gia cầm', 'Cấp 3', true, (SELECT id FROM professions WHERE code = '61')),
  ('613', 'Lao động trồng trọt và chăn nuôi hỗn hợp', 'Cấp 3', true, (SELECT id FROM professions WHERE code = '61')),
  ('614', 'Lao động lâm nghiệp', 'Cấp 3', true, (SELECT id FROM professions WHERE code = '61')),
  ('621', 'Lao động nuôi trồng thủy sản', 'Cấp 3', true, (SELECT id FROM professions WHERE code = '61')),
  ('622', 'Lao động khai thác thủy sản và đánh bẫy', 'Cấp 3', true, (SELECT id FROM professions WHERE code = '62')),
  ('631', 'Lao động trồng trọt tự cung tự cấp', 'Cấp 3', true, (SELECT id FROM professions WHERE code = '63')),
  ('711', 'Thợ xây dựng khung nhà và thợ khác có liên quan', 'Cấp 3', true, (SELECT id FROM professions WHERE code = '71')),
  ('712', 'Thợ hoàn thiện công trình xây dựng và các thợ liên quan', 'Cấp 3', true, (SELECT id FROM professions WHERE code = '71')),
  ('713', 'Thợ sơn, lau chùi tòa nhà và thợ liên quan', 'Cấp 3', true, (SELECT id FROM professions WHERE code = '71')),
  ('721', 'Thợ đúc, hàn, rèn và cán kim loại', 'Cấp 3', true, (SELECT id FROM professions WHERE code = '71')),
  ('722', 'Thợ rèn, thợ đóng dấu kim loại', 'Cấp 3', true, (SELECT id FROM professions WHERE code = '71')),
  ('731', 'Thợ chế tác sản phẩm chính xác', 'Cấp 3', true, (SELECT id FROM professions WHERE code = '71')),
  ('811', 'Thợ vận hành máy khai khoáng và chế biến khoáng sản', 'Cấp 3', true, (SELECT id FROM professions WHERE code = '81')),
  ('812', 'Thợ vận hành thiết bị xử lý và hoàn thiện kim loại', 'Cấp 3', true, (SELECT id FROM professions WHERE code = '81')),
  ('814', 'Thợ vận hành máy chế biến gỗ', 'Cấp 3', true, (SELECT id FROM professions WHERE code = '81')),
  ('815', 'Thợ vận hành thiết bị chế biến thực phẩm', 'Cấp 3', true, (SELECT id FROM professions WHERE code = '81')),
  ('821', 'Thợ lắp ráp cơ khí, điện và điện tử', 'Cấp 3', true, (SELECT id FROM professions WHERE code = '82')),
  ('831', 'Lái các phương tiện vận chuyển trên đường ray và công nhân liên quan', 'Cấp 3', true, (SELECT id FROM professions WHERE code = '83')),
  ('832', 'Lái xe con, xe tải và xe máy', 'Cấp 3', true, (SELECT id FROM professions WHERE code = '83')),
  ('833', 'Lái xe tải hạng nặng và xe buýt', 'Cấp 3', true, (SELECT id FROM professions WHERE code = '83')),
  ('911', 'Lao động dọn vệ sinh và giúp việc gia đình', 'Cấp 3', true, (SELECT id FROM professions WHERE code = '91')),
  ('920', 'Lao động giản đơn trong nông nghiệp, lâm nghiệp và thủy sản', 'Cấp 3', true, (SELECT id FROM professions WHERE code = '92')),
  ('931', 'Lao động giản đơn trong khai khoáng và xây dựng', 'Cấp 3', true, (SELECT id FROM professions WHERE code = '93')),
  ('932', 'Lao động giản đơn trong chế tạo', 'Cấp 3', true, (SELECT id FROM professions WHERE code = '93')),
  ('933', 'Lao động giản đơn trong giao thông và kho bãi', 'Cấp 3', true, (SELECT id FROM professions WHERE code = '93')),
  ('961', 'Người nhặt rác và thu gom phế liệu', 'Cấp 3', true, (SELECT id FROM professions WHERE code = '96')),
  ('962', 'Lao động giản đơn khác', 'Cấp 3', true, (SELECT id FROM professions WHERE code = '96'))
ON CONFLICT (code) DO UPDATE SET level = EXCLUDED.level, parent_id = EXCLUDED.parent_id;

-- Cấp 4 (100 nghề nghiệp)
INSERT INTO professions (code, name, level, status, parent_id) VALUES
  ('1721', 'Giám đốc, Phó Giám đốc đơn vị sản xuất (Nông nghiệp, lâm nghiệp và thủy sản)', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '172')),
  ('1722', 'Giám đốc, Phó Giám đốc đơn vị sản xuất (Khai khoáng, công nghiệp chế biến, chế tạo)', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '172')),
  ('1723', 'Giám đốc, Phó Giám đốc đơn vị sản xuất (Xây dựng)', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '172')),
  ('1724', 'Giám đốc, Phó Giám đốc đơn vị sản xuất (Bán buôn, bán lẻ)', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '172')),
  ('1725', 'Giám đốc, Phó Giám đốc đơn vị sản xuất (Dịch vụ lưu trú và ăn uống)', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '172')),
  ('1726', 'Giám đốc, Phó Giám đốc đơn vị sản xuất (Vận tải, kho bãi; Thông tin và truyền thông)', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '172')),
  ('1727', 'Giám đốc, Phó Giám đốc đơn vị sản xuất (Dịch vụ kinh doanh)', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '172')),
  ('1728', 'Giám đốc, Phó Giám đốc đơn vị sản xuất (Dịch vụ cá nhân và cộng đồng)', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '172')),
  ('1743', 'Giám đốc, Phó Giám đốc công ty nhỏ (Xây dựng)', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '174')),
  ('1742', 'Giám đốc, Phó Giám đốc công ty nhỏ (Khai khoáng, công nghiệp chế biến, chế tạo)', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '174')),
  ('2141', 'Kỹ sư công nghiệp chế biến, chế tạo', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '214')),
  ('2142', 'Kỹ sư xây dựng', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '214')),
  ('2143', 'Kỹ sư môi trường', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '214')),
  ('2144', 'Kỹ sư cơ học, cơ khí', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '214')),
  ('2146', 'Kỹ sư khai thác mỏ, luyện kim và các nghề liên quan', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '214')),
  ('2151', 'Kỹ sư điện', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '215')),
  ('2152', 'Kỹ sư điện tử', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '215')),
  ('2161', 'Kiến trúc sư và nhà quy hoạch đô thị', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '216')),
  ('2163', 'Nhà thiết kế sản phẩm và trang phục', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '216')),
  ('2263', 'Nhà chuyên môn về y tế nghề nghiệp và vệ sinh lao động', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '226')),
  ('3111', 'Kỹ thuật viên khoa học vật lý và kỹ thuật', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '311')),
  ('3112', 'Kỹ thuật viên xây dựng', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '311')),
  ('3113', 'Kỹ thuật viên điện', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '311')),
  ('3114', 'Kỹ thuật viên điện tử và viễn thông', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '311')),
  ('3115', 'Kỹ thuật viên cơ khí', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '311')),
  ('3117', 'Kỹ thuật viên khai thác mỏ và luyện kim', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '311')),
  ('3121', 'Giám sát viên khai thác mỏ', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '312')),
  ('3122', 'Giám sát viên sản xuất', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '312')),
  ('3123', 'Giám sát viên xây dựng', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '312')),
  ('3131', 'Người vận hành trạm hoặc nhà máy phát điện', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '313')),
  ('4110', 'Nhân viên văn phòng đa năng', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '411')),
  ('4120', 'Thư ký', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '412')),
  ('4311', 'Nhân viên kế toán', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '431')),
  ('4312', 'Nhân viên thống kê, tài chính và bảo hiểm', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '431')),
  ('4313', 'Nhân viên kế toán tiền lương', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '431')),
  ('4321', 'Nhân viên ghi chép tồn kho', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '432')),
  ('4322', 'Nhân viên sản xuất', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '432')),
  ('4323', 'Nhân viên vận chuyển', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '432')),
  ('4401', 'Nhân viên thư viện', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '440')),
  ('4406', 'Nhân viên tổ chức nhân sự', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '440')),
  ('5111', 'Tiếp viên trên tàu hoặc máy bay', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '511')),
  ('5120', 'Đầu bếp', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '512')),
  ('5131', 'Bồi bàn', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '513')),
  ('5141', 'Thợ làm tóc', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '514')),
  ('5142', 'Thợ làm đẹp và các thợ có liên quan', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '514')),
  ('5161', 'Nhân viên bảo vệ và an ninh', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '516')),
  ('5162', 'Nhân viên phòng chống cháy nổ', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '516')),
  ('5210', 'Người bán hàng tại quầy', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '521')),
  ('5320', 'Công nhân chăm sóc sức khỏe tại nhà', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '532')),
  ('5410', 'Nhân viên bảo vệ, cảnh sát tư nhân', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '541')),
  ('6110', 'Lao động trồng trọt', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '611')),
  ('6121', 'Lao động chăn nuôi gia súc', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '612')),
  ('6122', 'Lao động gia cầm', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '612')),
  ('6130', 'Lao động trồng trọt và chăn nuôi hỗn hợp', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '613')),
  ('6140', 'Lao động lâm nghiệp', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '614')),
  ('6210', 'Lao động nuôi trồng thủy sản', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '621')),
  ('6221', 'Lao động khai thác cá trong nội địa', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '622')),
  ('6223', 'Lao động khai thác thủy sản trong vùng biển Việt Nam', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '622')),
  ('6224', 'Lao động săn bắn, đánh bẫy', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '622')),
  ('6310', 'Lao động trồng trọt tự cung tự cấp', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '631')),
  ('7111', 'Thợ xây nhà', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '711')),
  ('7112', 'Thợ nề và các thợ có liên quan', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '711')),
  ('7121', 'Thợ lợp mái', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '712')),
  ('7122', 'Thợ lát sàn và thợ lát gạch', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '712')),
  ('7131', 'Thợ sơn và trát vữa', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '713')),
  ('7132', 'Thợ phun sơn và phủ sơn', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '713')),
  ('7211', 'Thợ đúc kim loại', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '721')),
  ('7212', 'Thợ hàn và thợ cắt kim loại bằng ngọn lửa', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '721')),
  ('7221', 'Thợ rèn, thợ đóng dấu và thợ dập khuôn', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '722')),
  ('7311', 'Thợ chế tác nhạc cụ chính xác', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '731')),
  ('8111', 'Thợ vận hành máy khai khoáng hầm lò', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '811')),
  ('8112', 'Thợ vận hành thiết bị chế biến khoáng sản và đá', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '811')),
  ('8121', 'Thợ vận hành thiết bị xử lý kim loại', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '812')),
  ('8141', 'Thợ vận hành máy chế biến gỗ', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '814')),
  ('8151', 'Thợ vận hành thiết bị chế biến thực phẩm', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '815')),
  ('8211', 'Thợ lắp ráp máy cơ khí', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '821')),
  ('8212', 'Thợ lắp ráp thiết bị điện và điện tử', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '821')),
  ('8311', 'Lái các phương tiện vận chuyển trên đường ray', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '831')),
  ('8322', 'Lái xe con, xe tải và xe máy', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '832')),
  ('8331', 'Lái xe tải hạng nặng', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '833')),
  ('9111', 'Người dọn dẹp, lau chùi tại cơ sở', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '911')),
  ('9201', 'Lao động trồng trọt giản đơn', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '920')),
  ('9202', 'Lao động chăn nuôi giản đơn', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '920')),
  ('9205', 'Lao động lâm nghiệp giản đơn', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '920')),
  ('9311', 'Lao động khai khoáng giản đơn', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '931')),
  ('9312', 'Lao động xây dựng giản đơn', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '931')),
  ('9321', 'Lao động đóng gói bằng tay', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '932')),
  ('9329', 'Lao động chế tạo giản đơn khác', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '932')),
  ('9331', 'Lao động vận hành xe thô sơ', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '933')),
  ('9621', 'Người đưa thư, phát tờ rơi và thông báo', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '962')),
  ('0110', 'Sĩ quan quân đội', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '011')),
  ('0120', 'Hạ sĩ quan, binh sĩ', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '012')),
  ('0130', 'Lực lượng khác trong quân đội', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '013')),
  ('0210', 'Sĩ quan công an', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '021')),
  ('0220', 'Hạ sĩ quan, chiến sĩ công an', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '022')),
  ('0230', 'Lực lượng khác trong công an', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '023')),
  ('0310', 'Cơ yếu', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '031')),
  ('0320', 'Lực lượng vũ trang khác', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '032')),
  ('9611', 'Người nhặt rác, thu gom phế liệu', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '961')),
  ('9629', 'Lao động giản đơn khác chưa được phân vào đâu', 'Cấp 4', true, (SELECT id FROM professions WHERE code = '962'))
ON CONFLICT (code) DO UPDATE SET level = EXCLUDED.level, parent_id = EXCLUDED.parent_id;


-- =================================================================
-- Seed: injury_type (Danh mục loại chấn thương - 2 cấp)
--       injury_factors (Yếu tố gây chấn thương - 1 cấp)
-- =================================================================

-- injury_type: Cấp 1 (nhóm chấn thương)
INSERT INTO injury_type (code, name, level, status, parent_id) VALUES
  ('01', 'Đầu, mặt, cổ', 'Cấp 1', true, NULL),
  ('02', 'Ngực, bụng', 'Cấp 1', true, NULL),
  ('03', 'Phần chi trên', 'Cấp 1', true, NULL),
  ('04', 'Phần chi dưới', 'Cấp 1', true, NULL),
  ('05', 'Bỏng', 'Cấp 1', true, NULL),
  ('06', 'Nhiễm độc', 'Cấp 1', true, NULL)
ON CONFLICT (code) DO UPDATE SET level = EXCLUDED.level, parent_id = EXCLUDED.parent_id;

-- injury_type: Cấp 2 (chi tiết chấn thương)
INSERT INTO injury_type (code, name, level, status, parent_id) VALUES
  ('011', 'Các chấn thương sọ não hở hoặc kín', 'Cấp 2', true, (SELECT id FROM injury_type WHERE code = '01')),
  ('012', 'Dập não', 'Cấp 2', true, (SELECT id FROM injury_type WHERE code = '01')),
  ('013', 'Máu tụ trong sọ', 'Cấp 2', true, (SELECT id FROM injury_type WHERE code = '01')),
  ('014', 'Vỡ sọ', 'Cấp 2', true, (SELECT id FROM injury_type WHERE code = '01')),
  ('015', 'Bị lột da đầu', 'Cấp 2', true, (SELECT id FROM injury_type WHERE code = '01')),
  ('016', 'Tổn thương đồng tử mắt', 'Cấp 2', true, (SELECT id FROM injury_type WHERE code = '01')),
  ('017', 'Vỡ và dập các xương cuốn của sọ', 'Cấp 2', true, (SELECT id FROM injury_type WHERE code = '01')),
  ('018', 'Vỡ các xương hàm mặt', 'Cấp 2', true, (SELECT id FROM injury_type WHERE code = '01')),
  ('019', 'Tổn thương phần mềm rộng ở mặt', 'Cấp 2', true, (SELECT id FROM injury_type WHERE code = '01')),
  ('0110', 'Bị thương vào cổ, tác hại đến thanh quản và thực quản', 'Cấp 2', true, (SELECT id FROM injury_type WHERE code = '01')),
  ('021', 'Tổn thương lồng ngực tác hại đến cơ quan bên trong', 'Cấp 2', true, (SELECT id FROM injury_type WHERE code = '02')),
  ('022', 'Hội chứng chèn ép trung thất', 'Cấp 2', true, (SELECT id FROM injury_type WHERE code = '02')),
  ('023', 'Dập lồng ngực hay lồng ngực bị ép nặng', 'Cấp 2', true, (SELECT id FROM injury_type WHERE code = '02')),
  ('024', 'Gãy xương sườn', 'Cấp 2', true, (SELECT id FROM injury_type WHERE code = '02')),
  ('025', 'Tổn thương phần mềm rộng ở bụng', 'Cấp 2', true, (SELECT id FROM injury_type WHERE code = '02')),
  ('026', 'Bị thương và dập mạnh ở bụng tác hại tới các cơ quan bên trong', 'Cấp 2', true, (SELECT id FROM injury_type WHERE code = '02')),
  ('027', 'Thủng, vỡ tạng trong ổ bụng', 'Cấp 2', true, (SELECT id FROM injury_type WHERE code = '02')),
  ('028', 'Đụng, dập, ảnh hưởng tới vận động của xương sống', 'Cấp 2', true, (SELECT id FROM injury_type WHERE code = '02')),
  ('029', 'Vỡ, trật xương sống', 'Cấp 2', true, (SELECT id FROM injury_type WHERE code = '02')),
  ('0210', 'Vỡ xương chậu', 'Cấp 2', true, (SELECT id FROM injury_type WHERE code = '02')),
  ('0211', 'Tổn thương xương chậu ảnh hưởng lớn tới vận động của thân và chi dưới', 'Cấp 2', true, (SELECT id FROM injury_type WHERE code = '02')),
  ('0212', 'Tổn thương cơ quan sinh dục', 'Cấp 2', true, (SELECT id FROM injury_type WHERE code = '02')),
  ('031', 'Tổn thương xương, thần kinh, mạch máu ảnh hưởng tới vận động của chi trên', 'Cấp 2', true, (SELECT id FROM injury_type WHERE code = '03')),
  ('032', 'Tổn thương phần mềm rộng khắp ở các chi trên', 'Cấp 2', true, (SELECT id FROM injury_type WHERE code = '03')),
  ('033', 'Tổn thương ở vai, cánh tay, bàn tay, cổ tay làm hại đến các gân', 'Cấp 2', true, (SELECT id FROM injury_type WHERE code = '03')),
  ('034', 'Dập, gẫy, vỡ nát các xương đòn, bả vai, cánh tay, cẳng tay, cổ tay, bàn tay, đốt ngón tay', 'Cấp 2', true, (SELECT id FROM injury_type WHERE code = '03')),
  ('035', 'Trật, trẹo các khớp xương', 'Cấp 2', true, (SELECT id FROM injury_type WHERE code = '03')),
  ('041', 'Chấn thương ở các chi dưới gây tổn thương mạch máu, thần kinh, xương ảnh hưởng tới vận động', 'Cấp 2', true, (SELECT id FROM injury_type WHERE code = '04')),
  ('042', 'Bị thương rộng khắp ở chi dưới', 'Cấp 2', true, (SELECT id FROM injury_type WHERE code = '04')),
  ('043', 'Gẫy và dập xương hông, khớp hông, đùi, đầu gối, ống, cổ chân, bàn chân và các ngón', 'Cấp 2', true, (SELECT id FROM injury_type WHERE code = '04')),
  ('051', 'Bỏng độ 3', 'Cấp 2', true, (SELECT id FROM injury_type WHERE code = '05')),
  ('052', 'Bỏng do nhiệt rộng khắp độ 2, độ 3', 'Cấp 2', true, (SELECT id FROM injury_type WHERE code = '05')),
  ('053', 'Bỏng nặng do hóa chất độ 2, độ 3', 'Cấp 2', true, (SELECT id FROM injury_type WHERE code = '05')),
  ('054', 'Bỏng điện nặng', 'Cấp 2', true, (SELECT id FROM injury_type WHERE code = '05')),
  ('055', 'Bị bỏng lạnh độ 3', 'Cấp 2', true, (SELECT id FROM injury_type WHERE code = '05')),
  ('056', 'Bị bỏng lạnh rộng khắp độ 2, độ 3', 'Cấp 2', true, (SELECT id FROM injury_type WHERE code = '05')),
  ('061', 'Nhiễm độc ô xít các bon nặng (ngất, mê sảng, rối loạn dinh dưỡng da, sưng phổi...)', 'Cấp 2', true, (SELECT id FROM injury_type WHERE code = '06')),
  ('062', 'Nhiễm độc ô xít nitơ nặng (sưng phổi, viêm phế quản...)', 'Cấp 2', true, (SELECT id FROM injury_type WHERE code = '06')),
  ('063', 'Nhiễm độc hydro sunfua nặng (kích thích mạnh, động kinh, sưng phổi, mê sảng)', 'Cấp 2', true, (SELECT id FROM injury_type WHERE code = '06')),
  ('064', 'Nhiễm độc ô xít các bon níc nồng độ cao (ngừng thở, chảy máu, ngất)', 'Cấp 2', true, (SELECT id FROM injury_type WHERE code = '06')),
  ('065', 'Nhiễm độc cấp các loại hóa chất bảo vệ thực vật', 'Cấp 2', true, (SELECT id FROM injury_type WHERE code = '06')),
  ('066', 'Nhiễm độc các loại hóa chất độc khác thuộc danh mục phải khai báo, đăng ký', 'Cấp 2', true, (SELECT id FROM injury_type WHERE code = '06'))
ON CONFLICT (code) DO UPDATE SET level = EXCLUDED.level, parent_id = EXCLUDED.parent_id;

-- injury_factors: Yếu tố gây chấn thương (1 cấp, không có parent)
INSERT INTO injury_factors (code, name, status) VALUES
  ('1', 'Điện (bao gồm điện cao thế)', true),
  ('2', 'Phóng xạ', true),
  ('3', 'Do phương tiện vận tải', true),
  ('4', 'Do thiết bị chịu áp lực', true),
  ('5', 'Do thiết bị nâng, thang máy', true),
  ('6', 'Nổ vật liệu nổ', true),
  ('7', 'Máy móc, thiết bị cán, cuốn, kẹp, cắt, va đập', true),
  ('8', 'Bỏng hoá chất', true),
  ('9', 'Ngộ độc hoá chất', true),
  ('10', 'Cháy nổ xăng dầu', true),
  ('11', 'Sập đổ công trình', true),
  ('12', 'Sập lò, sập đất đá trong xây dựng, khai thác, thăm dò khoáng sản', true),
  ('13', 'Cây hoặc vật đổ, đè, rơi', true),
  ('14', 'Ngã cao', true),
  ('15', 'Chết đuối', true),
  ('16', 'Các loại khác', true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO accident_causes (code, name, cause_group, status) VALUES
  -- Do người sử dụng lao động (mã 1-6)
  ('1', 'Không có thiết bị an toàn hoặc thiết bị không đảm bảo an toàn', 'EMPLOYER', true),
  ('2', 'Không có phương tiện bảo vệ cá nhân hoặc phương tiện bảo vệ cá nhân không tốt', 'EMPLOYER', true),
  ('3', 'Tổ chức lao động không hợp lý', 'EMPLOYER', true),
  ('4', 'Chưa huấn luyện hoặc huấn luyện an toàn vệ sinh lao động chưa đầy đủ', 'EMPLOYER', true),
  ('5', 'Không có quy trình an toàn hoặc biện pháp làm việc an toàn', 'EMPLOYER', true),
  ('6', 'Điều kiện làm việc không tốt', 'EMPLOYER', true),
  -- Do người lao động (mã 7-9)
  ('7', 'Quy phạm nội quy, quy trình, quy chuẩn, biện pháp làm việc an toàn', 'EMPLOYEE', true),
  ('8', 'Không sử dụng phương tiện bảo vệ cá nhân', 'EMPLOYEE', true),
  ('9', 'Khách quan khó tránh / Nguyên nhân chưa kể đến', 'OTHER', true)
ON CONFLICT (code) DO NOTHING;